apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homes
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-673efbae.efs.eu-west-1.amazonaws.com
    path: "/"
