apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: memcached-session-store-{{.Username}}
  labels:
    app: memcached-session-store-{{.Username}}
spec:
  replicas: 3
  serviceName: mss-{{.Username}}
  template:
    metadata:
      labels:
        app: memcached-session-store-{{.Username}}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: memcached
        image: memcached:1.4.32
        command:
        - memcached
        - -m 64
        - -vvv
        ports:
        - name: memcache
          containerPort: 11211
        livenessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
