apiVersion: v1
kind: Service
metadata:
  name: mss-{{.Username}}
  labels:
    app: memcached-session-store-{{.Username}}
spec:
  ports:
  - name: memcache
    port: 11211
  clusterIP: None
  selector:
    app: memcached-session-store-{{.Username}}
