apiVersion: batch/v1
kind: Job
metadata:
  name: create-user
  namespace: user-{{.Username}}
spec:
  template:
    metadata:
      name: create-user
    spec:
      containers:
      - name: create-user
        image: ubuntu:16.04
        command: ["useradd", "-u", "1001", "-g", "1001", "-m",
                  "-d", "/home/{{.Username}}", "{{.Username}}"]
        volumeMounts:
          - name: homes
            mountPath: "/home"
      restartPolicy: Never
      volumes:
      - name: homes
        persistentVolumeClaim:
          claimName: nfs-homes
