kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-home
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      user: {{.Username}}
  resources:
    requests:
      storage: 10Gi
