apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "{{.RequestCPU}}"
    requests.memory: {{.RequestMemory}}
    limits.cpu: "{{.LimitCPU}}"
    limits.memory: {{.LimitMemory}}
