apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu
  namespace: user-{{.Username}}
  labels:
    app: ubuntu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:16.04
        command:
          - /bin/sh
          - -c
          - "while true; do sleep; done"
        volumeMounts:
          - name: home
            mountPath: "/home"
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: nfs-homes
