apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: r-studio-{{.Username}}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - r-studio.{{.Username}}.users.analytics.kops.integration.dsd.io
    secretName: users-{{.Username}}-rstudio-tls
  rules:
  - host: r-studio.{{.Username}}.users.analytics.kops.integration.dsd.io
    http:
      paths:
      - backend:
          serviceName: r-studio-{{.Username}}
          servicePort: 80
        path: /
