apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: r-shiny-example
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - rshiny.apps.k8s-kops-test.integration.dsd.io
    secretName: rshiny-tls
  rules:
  - host: rshiny.apps.k8s-kops-test.integration.dsd.io
    http:
      paths:
      - backend:
          serviceName: r-shiny-example
          servicePort: 80
        path: /
