apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - jenkins.apps.analytics.kops.integration.dsd.io
    secretName: analytics-jenkins-tls
  rules:
  - host: jenkins.apps.analytics.kops.integration.dsd.io
    http:
      paths:
      - backend:
          serviceName: ironic-lion-jenkins
          servicePort: 8080
        path: /
