kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: r-studio-nfs-server-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
