apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-{{.Username}}
  labels:
    user: {{.Username}}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{.EFSHostname}}
    path: "/{{.Username}}"
